FROM oven/bun:1

ARG DATABASE_URL
ENV DATABASE_URL=${DATABASE_URL}
ENV PORT=3000

WORKDIR /apps
 
COPY package.json ./
COPY bun.lock ./
COPY turbo.json ./
COPY apps/web/package.json apps/web/package.json
COPY packages/db/package.json packages/db/package.json
COPY packages/eslint-config/package.json packages/eslint-config/package.json
COPY packages/typescript-config/package.json packages/typescript-config/package.json
COPY packages/ui/package.json packages/ui/package.json

RUN bun ci

COPY . .

RUN cd packages/db && bunx prisma generate
RUN cd apps/web && bun run build

WORKDIR /apps/apps/web

EXPOSE 3000

CMD [ "bun", "run", "start" ]

