## build the docker code
## push the docker image to docker hub
## SSH into our VM and start the new image

name: Deploy the backend

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with: 
          context: .
          file: ./docker/Dockerfile.backend
          push: true
          tags: divyanshthakurx/deploy-monorepo-backend:${{ github.sha }}

      - name: SSH and deploy to VM
          uses: appleboy/ssh-action@v1.0.3
          with:
            host: ${{ secrets.VM_HOST }}
            username: ${{ secrets.VM_USERNAME }}
            key: ${{ secrets.VM_SSH_KEY }}
            script: |
              sudo docker pull divyanshthakurx/deploy-monorepo-backend:${{ github.sha }}
              sudo docker stop backend || true
              sudo docker rm backend || true
              sudo docker run -d \
                --name backend \
                --restart always \
                -p 8080:8080 \
                divyanshthakurx/deploy-monorepo-frontend:${{ github.sha }}
              sudo docker image prune -af

        
